println("programa descuentos para una tienda ")
println("1.BOLA BLANCA")
println("2. BOLA VERDE")
println("3. BOLA AMARILLA")
println("4. BOLA AZUL")
println("5. BOLA ROJA")
val op = readInt()
val tc = op match {
	case 1 =>println("ingrese total de compra")
	val tc = readInt() 
	println("total a pagar")
	println(tc)

	case 2 => println("ingrese total de compra")
	val tc = readInt() 
	println("total a pagar")
	println(tc-((tc*10)/100))
	case 3 => println("ingrese total de compra")
	val tc = readInt() 
	println("total a pagar")
	println(tc-((tc*25)/100))
	case 4 => println("ingrese total de compra")
	val tc = readInt() 
	println("total a pagar")
	println(tc-((tc*50)/100))
	case 5 => println("ingrese total de compra")
	val tc = readInt() 
	println("total a pagar")
	println(tc-((tc*100)/100))
}

